spring:
  application:
    name: LibraryApi

  jpa:
    hibernate:
      ddl-auto: create  #Cria o Banco de Dados automaticamente se baseando na ORM
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
